### ISSUE TITLE
error in fasttext model with foreign language

### ISSUE THREAD

**Issue by samreenkazi** [lintseju/word_embedding#1]
Hello,
while creating fasttext model for foreign language , i have encountered following error.

`[2019-05-21 18:33:12,275] Training model fasttext
Traceback (most recent call last):
  File "train.py", line 53, in <module>
    main()
  File "train.py", line 36, in main
    model = FastText(wiki_sentences, sg=1, hs=1, size=args.size, workers=12, iter=5, min_count=10)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\fasttext.py", line 401, in __init__
    self.wv = FastTextKeyedVectors(size, min_n, max_n, bucket, compatible_hash)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\keyedvectors.py", line 1964, in __init__
    super(FastTextKeyedVectors, self).__init__(vector_size=vector_size)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\keyedvectors.py", line 376, in __init__
    super(WordEmbeddingsKeyedVectors, self).__init__(vector_size=vector_size)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\keyedvectors.py", line 214, in __init__
    self.vectors = zeros((0, vector_size))
TypeError: 'str' object cannot be interpreted as an integer

`

**Comment by lintseju** [comment]
Hi @samreenkazi,

Could you provide the argument you pass to the program? It seems that you pass a string for "--size", but it should be an integer.

**Comment by samreenkazi** [comment]
-- size 300 as written in read me , what i did was that casted it with int(size) and it fixed problem
but am getting another error now
`[2019-05-21 22:06:18,216] Save trained word vectors
Traceback (most recent call last):
  File "train.py", line 53, in <module>
    main()
  File "train.py", line 44, in main
    f.write('%d %d\n' % (len(model.wv.vocab), args.size))
TypeError: %d format: a number is required, not str
`

**Comment by samreenkazi** [comment]
this is how i fixed it
`model = FastText(wiki_sentences, sg=1, hs=1, size=**int(args.size),** workers=12, iter=5, min_count=10)`

**Comment by lintseju** [comment]
For quick fix, you can modify line 44 to `f.write('%d %d\n' % (len(model.wv.vocab), int(args.size)))` (also cast args.size to int)
Could you provide your os, os version, python version, command you use and other information may cause this problem, so I can fix the bug in a better way?
Thank you.

**Comment by samreenkazi** [comment]
hello @lintseju 
I am using windows 10,python 3.6.1,command i have used was
`python train.py --lang ur --model fasttext --size 300 --output data/ur_wiki_fasttext_300.txt
`
there was another bug in program, with foreign language we have to specify encoding='utf-8' argument as well while opening file in line 43 as
`with open(args.output, 'w',encoding='utf-8')`
 I have few more questions,did this code subsample frequent words ,is negative sampling performed and what does in_qsize 7, out_qsize 0 refere to while training.
how can we context window in it.
regards

**Comment by samreenkazi** [comment]
hello @lintseju 
after successfuly training foreign language with fasttext I tried executing demo.py ,vy tweaking it little bit for language of my intrest,
lang = 'ur'
    demo_nearest = ['ملکہ','عورت','مرد','بادشاہ']
    demo_country = [
            ('انگلستان', 'لندن'),
            ('بھارت','بمبئی'),
            ('پاکستان', 'اسلامآباد'),
            ('جپان', 'ٹوکیو'),
            ('ملکہ','ایلزبتھ')]
this way, I am getting similarities of demo_nearest words but its giving me error in plotting country/capital analogy.

 <ipython-input-28-ecd1553792d2> in main()
     39     for country, capital in demo_country:
     40         x_pca.append(vectors[words.index(country)])
---> 41         x_pca.append(vectors[words.index(capital)])
     42 
     43     # workaround for cannot show Chinese by matplotlib

ValueError: 'اسلامآباد' is not in list

**Comment by lintseju** [comment]
Hi
Thanks for your help, I fixed those bugs.
For other question:
It use negative sampling, I use gensim's implementation so you can check its parameter [here](https://radimrehurek.com/gensim/models/fasttext.html)
It also have parameter to set context window and ignore infrequent words.
in_qsize and out_qsize are internal log for training, you can ignore it.

For the fail in demo.py
It means 'اسلامآباد' not in your corpus. If language "ur" is not seperate its word by space, you should use a tokenizer to split the sentence. Which tokenizer to use is language dependent, you can refer to [here](https://github.com/facebookresearch/fastText/blob/master/docs/crawl-vectors.md#tokenization) based on your language. And add your tokenization code into wiki.py:WikiSentences.\_\_iter\_\_
